// SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0

// Command qa-codex-hooks registers the QA recorder as a Codex hook, for every
// event the plugin itself registers, with the trust entries Codex needs to run
// it without a /hooks prompt.
//
// It exists because Codex enforces hook trust and there is no supported API to
// request it: a hook whose trusted_hash is absent or stale is skipped silently.
// install-codex.sh solves that for the plugin's own hooks with the binary's
// `emit-codex-hooks` subcommand. The recorder is not the plugin, so it needs the
// same treatment from somewhere, and this is that somewhere.
//
// It is deliberately not a second copy of the hash rule. It calls
// codex.TrustHash and walks codex.HookEvents, so the recorder is registered for
// exactly the events the plugin acts on and is trusted by exactly the rule the
// product reproduces. A change to either shows up here as a build failure or a
// missing event, not as a QA run that silently records nothing.
//
// Two constraints the caller must respect, both checked:
//
//  1. The config file must not already declare hooks. The trust key embeds the
//     group index, this block always takes index 0, and a pre-existing group
//     would make that wrong. So this runs first, into a fresh config, and
//     `emit-codex-hooks` runs second and counts this block as the group it is.
//  2. The markers are the QA ones, not the plugin's. codex.StripManagedBlock
//     removes anything between the plugin's markers before counting groups, so a
//     recorder block wearing them would be invisible to the count and the plugin
//     would take index 0 too — two groups claiming one trust key.
//
// Usage:
//
//	qa-codex-hooks --command <hook command> --config <path to config.toml> >> <path to config.toml>
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dash0hq/dash0-agent-plugin/internal/source/codex"
)

const (
	blockBegin = "# >>> dash0 QA recorder (generated by qa-codex-hooks) >>>"
	blockEnd   = "# <<< dash0 QA recorder <<<"
	// The group index this block claims. Always 0: see constraint 1 above.
	groupIndex = 0
)

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintf(os.Stderr, "qa-codex-hooks: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string, out *os.File) error {
	fs := flag.NewFlagSet("qa-codex-hooks", flag.ContinueOnError)
	command := fs.String("command", "", "exact hook command string Codex will run")
	configPath := fs.String("config", "", "absolute path of the config.toml this block is appended to")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *command == "" || *configPath == "" {
		return fmt.Errorf("--command and --config are both required")
	}
	if strings.Contains(*command, "'") {
		return fmt.Errorf("hook command contains a single quote, which cannot be written as a TOML literal string: %q", *command)
	}

	// Codex realpath's its config before building the trust key, so the key must
	// carry the resolved path or the entry is never found and the hook is treated
	// as untrusted. The file may not exist yet, so resolve the directory.
	keyPath := *configPath
	if resolvedDir, err := filepath.EvalSymlinks(filepath.Dir(*configPath)); err == nil {
		keyPath = filepath.Join(resolvedDir, filepath.Base(*configPath))
	}

	// Constraint 1. A config that already declares a hook group would make this
	// block's index wrong, and a wrong index fails as silence: Codex runs the
	// session, skips the recorder, and the run reports zero recorded hooks.
	if data, err := os.ReadFile(*configPath); err == nil {
		if strings.Contains(string(data), "[[hooks.") {
			return fmt.Errorf("%s already declares a hook group; this block must be the first, "+
				"because its trust key claims group index %d", *configPath, groupIndex)
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("reading %s: %w", *configPath, err)
	}

	block, err := render(keyPath, *command)
	if err != nil {
		return err
	}
	_, err = fmt.Fprint(out, block)
	return err
}

// render returns the marker-delimited TOML: one [[hooks.<Event>]] group per
// event the plugin registers, plus the matching trust entry for each.
//
// The shape mirrors codex.RenderManagedBlock, which is the reproduction of
// Codex's own normalization that the e2e canary keeps honest. Two deliberate
// differences: the markers, and no statusMessage. statusMessage participates in
// the hash, and an absent one is dropped from the hashed identity rather than
// hashed as empty, so omitting it here is a whole value fewer to keep in step
// with the product.
func render(configPath, command string) (string, error) {
	var hooks, state strings.Builder
	hooks.WriteString(blockBegin + "\n")
	hooks.WriteString("# The QA recorder, registered alongside the plugin. Removed with the run's scratch home.\n")

	for _, event := range codex.HookEvents {
		fmt.Fprintf(&hooks, "\n[[hooks.%s]]\nmatcher = \"*\"\n[[hooks.%s.hooks]]\ntype = \"command\"\ncommand = '%s'\n",
			event.ConfigName, event.ConfigName, command)

		// matcher = "*" is written for every event, but Codex normalizes it away
		// for the events that have nothing to match on, and the hash has to follow
		// that rather than what the block says.
		hash, err := codex.TrustHash(event.KeyLabel, event.HasMatcher, command, "")
		if err != nil {
			return "", fmt.Errorf("hashing %s: %w", event.ConfigName, err)
		}
		fmt.Fprintf(&state, "\n[hooks.state.%q]\ntrusted_hash = \"%s\"\n",
			fmt.Sprintf("%s:%s:%d:0", configPath, event.KeyLabel, groupIndex), hash)
	}

	hooks.WriteString(state.String())
	hooks.WriteString("\n" + blockEnd + "\n")
	return hooks.String(), nil
}
