"""The slug conformance vectors: the inputs, and how the file is produced (#294).

`docs/slug-vectors.json` is the published contract for anyone computing this
plugin's slug from another language. It exists because a prose spec drifts from
`scripts/lib-slug.sh` and still reads as current, and because a hand-maintained
table of expected values is a SECOND IMPLEMENTATION — the exact thing the file
is meant to delete. So:

* the INPUTS below are hand-curated (an input list is not an implementation);
* every expected slug is GENERATED by running the real `session_dir_slug`; and
* `tests/test_slug_vectors_294.py` regenerates the whole file and asserts the
  checked-in bytes are what the implementation produces today.

That last point is the entire guarantee. The file cannot drift from the code
without the suite going red, so an external port that diffs against it is
diffing against something our CI is already holding still.

What the vectors CANNOT do, stated plainly: they are generated from the
implementation, so they can never catch a bug IN it. Correctness against Claude
Code's own `JXA` is pinned separately, by the independent transcription in
`tests/test_slug_parity.py`. These vectors pin *agreement*, not *truth*.

Regenerate with::

    python3 -m tests.slug_vectors

── The two environment axes ──────────────────────────────────────────────────

**cygpath.** `session_dir_slug` runs `cygpath -w` when it is on PATH, so an
MSYS-shaped path (`/c/dev/x`) slugs one way with cygpath and another without.
Every input is therefore generated twice. When both runs agree the vector is
`"cygpath": "agnostic"` — verified, not asserted by hand. When they disagree the
input yields two vectors, `"present"` and `"absent"`. A port with no cygpath in
the picture (any PowerShell caller holding a native `C:\\dev\\x`) wants the
`agnostic` and `absent` vectors; the `present` ones describe what the shell does
to an MSYS path on its way in.

The `present` vectors are generated against `tests/cygpath_stub.py`, a MODEL of
cygpath, not a real one. That is a real limitation and it is recorded in the
file itself.

**The UTF-8 decoder.** For an ill-formed path the shell hands off to
`pipeline/slug.py`, but only where such a path can exist: on Linux always, and
elsewhere only under `REMEMBER_UTF8_STRICT=1`. So an ill-formed input has no
single answer across platforms. Generation forces `REMEMBER_UTF8_STRICT=1`
throughout — which changes nothing for a well-formed path, and makes the
ill-formed ones platform-stable — and those vectors carry the flag in
`requires`. A Windows port can ignore them outright: Windows paths come from
UTF-16 and cannot be ill-formed.
"""

from __future__ import annotations

import base64
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from .cygpath_stub import CYGPATH_STUB

REPO_ROOT = Path(__file__).resolve().parent.parent
LIB_SLUG_SH = REPO_ROOT / "scripts" / "lib-slug.sh"
VECTOR_FILE = REPO_ROOT / "docs" / "slug-vectors.json"

FORMAT_VERSION = 1
SLUG_MAX = 200

# ── Inputs ───────────────────────────────────────────────────────────────────
# Every shape the suite already parametrizes, plus the two the issue is about.
# Curated by hand on purpose: an input list is a list of questions, and only the
# ANSWERS would be a second implementation.

_WIN_TAIL = "Users\\ricky\\dev\\jqit\\project-b"
_POSIX_TAIL = "Users/ricky/dev/jqit/project-b"

# The reporter's shape: deep enough that the native Win32 form crosses MAX_PATH.
# 3 + 1 + 130 + 1 + 130 = 265 characters.
_LONG_TAIL = "a" * 130 + "\\" + "b" * 130
_WIN_LONG = "C:\\dev\\" + _LONG_TAIL
_MSYS_LONG = "/c/dev/" + _LONG_TAIL.replace("\\", "/")
_UNC_LONG = "\\\\server\\share\\" + _LONG_TAIL
_MSYS_UNC_LONG = "//server/share/" + _LONG_TAIL.replace("\\", "/")

# Deep enough to cross 200 characters without anything exotic — a monorepo
# module path under a long home directory, which is how #157 was hit.
_DEEP = "/Users/a-developer-with-a-long-name/Documents/clients/acme-holdings/" + "/".join(
    f"packages/module-{i}" for i in range(12)
)


def _u(text: str) -> bytes:
    return text.encode("utf-8")


INPUTS: list[dict] = [
    # ── Ordinary POSIX ───────────────────────────────────────────────────────
    {"id": "posix-home", "raw": _u("/home/u/p"), "note": ""},
    {"id": "posix-macos", "raw": _u("/Users/f/Documents/dvsi"), "note": ""},

    # ── The five Windows drive shapes #263 pinned, plus /cygdrive ────────────
    # These slugs name stores that exist on disk today. A change to any of them
    # is a rename, not a fix.
    {"id": "win-msys", "raw": _u("/c/" + _POSIX_TAIL),
     "note": "the shape a Git Bash hook is handed"},
    {"id": "win-drive-lower-slash", "raw": _u("c:/" + _POSIX_TAIL), "note": ""},
    {"id": "win-drive-upper-slash", "raw": _u("C:/" + _POSIX_TAIL), "note": ""},
    {"id": "win-drive-lower-back", "raw": _u("c:\\" + _WIN_TAIL), "note": ""},
    {"id": "win-drive-upper-back", "raw": _u("C:\\" + _WIN_TAIL),
     "note": "the native Win32 form a PowerShell caller already holds"},
    {"id": "win-cygdrive", "raw": _u("/cygdrive/c/" + _POSIX_TAIL), "note": ""},

    # ── UNC ──────────────────────────────────────────────────────────────────
    {"id": "unc-msys", "raw": _u("//server/share/project"), "note": ""},
    {"id": "unc-native", "raw": _u("\\\\server\\share\\project"),
     "note": "the two leading separators are two dashes"},

    # ── Past MAX_PATH: cygpath answers in the long-path spelling (#294) ──────
    {"id": "win-long-msys", "raw": _u(_MSYS_LONG),
     "note": "cygpath -w returns \\\\?\\C:\\... here; the prefix is stripped before the fold"},
    {"id": "win-long-native", "raw": _u(_WIN_LONG), "note": ""},
    {"id": "unc-long-msys", "raw": _u(_MSYS_UNC_LONG),
     "note": "cygpath -w returns \\\\?\\UNC\\..., which maps back to \\\\, not to nothing"},
    {"id": "unc-long-native", "raw": _u(_UNC_LONG), "note": ""},

    # ── The 200-character truncation and its hash (#157) ─────────────────────
    {"id": "truncate-boundary-199", "raw": _u("a" * 199), "note": "one under the limit — no hash"},
    {"id": "truncate-boundary-200", "raw": _u("a" * 200), "note": "exactly the limit — still no hash"},
    {"id": "truncate-boundary-201", "raw": _u("a" * 201), "note": "one over — the first truncated case"},
    {"id": "truncate-deep-project", "raw": _u(_DEEP), "note": "how #157 was actually hit"},
    {"id": "truncate-separators", "raw": _u("/x" * 150), "note": ""},

    # ── Non-ASCII: the regex has no /u flag, so it counts UTF-16 code units ──
    {"id": "nonascii-latin", "raw": _u("/tmp/café/projet"), "note": "BMP — one dash"},
    {"id": "nonascii-cjk", "raw": _u("/tmp/日本語/プロジェクト"), "note": "BMP — one dash each"},
    {"id": "nonascii-emoji", "raw": _u("/tmp/emoji-🎉-dir"),
     "note": "astral — a surrogate PAIR, so TWO dashes"},
    {"id": "nonascii-astral-kanji", "raw": _u("/tmp/𠮷野家/x"),
     "note": "Extension-B kanji — astral, two dashes"},
    {"id": "nonascii-mixed", "raw": _u("/tmp/mixed-é-🎉-日-𠮷/deep"), "note": ""},
    {"id": "nonascii-astral-truncating", "raw": _u("/tmp/" + "🎉" * 120),
     "note": "astral AND over the limit: the hash is of the ORIGINAL path"},

    # ── The invariants that keep this a Windows-only conversion ─────────────
    {"id": "drive-letter-not-at-start", "raw": _u("/tmp/x/C:/y"),
     "note": "an embedded X: is an ordinary colon, never folded"},
    {"id": "looks-long-path-prefixed", "raw": _u("/tmp/\\\\?\\C:/x"),
     "note": "a backslash is an ordinary filename byte on Linux; the strip is confined to what cygpath produced"},
    {"id": "newline-in-path", "raw": _u("/tmp/a\nb"),
     "note": "legal in a POSIX filename, and sed's own record separator"},

    # ── Ill-formed UTF-8 (#186) — see the module docstring ──────────────────
    {"id": "illformed-latin1", "raw": b"/tmp/caf\xe9/x",
     "note": "a legacy-encoded byte; the decoder emits one replacement character"},
    {"id": "illformed-truncated-lead", "raw": b"/tmp/\xe6\x97/x",
     "note": "a 3-byte lead with only one continuation — maximal-subpart, one replacement"},
]


# ── Running the real implementation ──────────────────────────────────────────

_STUB_DIR: Path | None = None


def _stub_dir() -> Path:
    """A directory holding the cygpath stub, made once per process."""
    global _STUB_DIR
    if _STUB_DIR is None:
        d = Path(tempfile.mkdtemp(prefix="remember-cygpath-stub-"))
        stub = d / "cygpath"
        stub.write_text(CYGPATH_STUB, encoding="utf-8")
        stub.chmod(0o755)
        _STUB_DIR = d
    return _STUB_DIR


def real_cygpath_on_path() -> bool:
    """A real cygpath makes the no-cygpath half of every vector unproducible."""
    return shutil.which("cygpath") is not None


def bash_slug(raw: bytes, *, cygpath: bool) -> str:
    """`session_dir_slug` as a hook runs it, on raw argv bytes.

    Bytes rather than str because the ill-formed inputs have no str form that
    survives a round trip, and because argv is bytes on POSIX anyway.
    """
    env = dict(os.environ)
    env["PIPELINE_DIR"] = str(REPO_ROOT)
    # Forced, both ways: it changes nothing for a well-formed path, and it is
    # what makes the ill-formed ones answer the same on macOS and on Linux.
    env["REMEMBER_UTF8_STRICT"] = "1"
    if cygpath:
        env["PATH"] = f"{_stub_dir()}{os.pathsep}{env['PATH']}"

    script = f'source "{LIB_SLUG_SH}"\nsession_dir_slug "$1"\n'
    result = subprocess.run(
        ["bash", "-c", script, "bash", raw],
        env=env, capture_output=True, timeout=60,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.decode("utf-8", "replace"))
    return result.stdout.decode("ascii").rstrip("\n")


# ── Building the document ────────────────────────────────────────────────────

COMMENT = [
    "Conformance vectors for claude-remember's session-directory slug.",
    "",
    "THIS FILE IS GENERATED. Do not hand-edit it: run `python3 -m tests.slug_vectors`.",
    "Every expected value here was produced by running scripts/lib-slug.sh, and",
    "tests/test_slug_vectors_294.py regenerates the whole file on every CI run and",
    "fails if the checked-in bytes differ. It therefore cannot drift from the",
    "implementation without our own suite going red — which is the point: an",
    "external port that diffs against this file is diffing against something we",
    "are already holding still.",
    "",
    "Each vector:",
    "  id        - stable name. Suffixed .cygpath / .no-cygpath where the two differ.",
    "  path      - the input, when it is valid UTF-8. null when it is not.",
    "  path_b64  - the input as raw bytes, base64. ALWAYS present, and authoritative.",
    "  slug      - the expected result. Always ASCII [A-Za-z0-9-].",
    "  cygpath   - agnostic: same answer whether or not cygpath is on PATH.",
    "              present:  only holds with cygpath (an MSYS path being converted).",
    "              absent:   only holds without it.",
    "  truncated - true when the slug passed 200 characters and carries a hash.",
    "  requires  - what must be available to reproduce this with the shell version.",
    "  note      - why the case is here.",
    "",
    "If you are porting: the vectors you want are cygpath=agnostic and",
    "cygpath=absent. Those describe the pure function - fold a leading upper-case",
    "ASCII drive letter, replace every non-[A-Za-z0-9] UTF-16 CODE UNIT with a",
    "dash (so an astral character costs two), and past 200 characters keep the",
    "first 200 and append base36(abs(int32(hash))) of the ORIGINAL path.",
    "The cygpath=present vectors describe what the shell does to an MSYS-shaped",
    "path on its way in, and they are generated against a MODEL of cygpath",
    "(tests/cygpath_stub.py), not a real one.",
    "",
    "Vectors requiring 'utf8-decoder' are ill-formed UTF-8. The shell only",
    "consults the decoder where such a path can exist - on Linux always,",
    "elsewhere only under REMEMBER_UTF8_STRICT=1, which is how these were",
    "generated. A Windows port can ignore them: Windows paths come from UTF-16.",
]


def _vector(spec: dict, cygpath: str, slug: str) -> dict:
    raw: bytes = spec["raw"]
    try:
        path = raw.decode("utf-8")
        well_formed = True
    except UnicodeDecodeError:
        path = None
        well_formed = False

    requires: list[str] = []
    if cygpath == "present":
        requires.append("cygpath")
    if not well_formed:
        requires.extend(["utf8-decoder", "iconv", "python3"])
    if len(slug) > SLUG_MAX:
        requires.append("python3")

    suffix = {"agnostic": "", "present": ".cygpath", "absent": ".no-cygpath"}[cygpath]
    return {
        "id": spec["id"] + suffix,
        "path": path,
        "path_b64": base64.b64encode(raw).decode("ascii"),
        "slug": slug,
        "cygpath": cygpath,
        "truncated": len(slug) > SLUG_MAX,
        "requires": sorted(set(requires)),
        "note": spec["note"],
    }


def generate() -> dict:
    """Run every input through the real implementation, both ways."""
    vectors: list[dict] = []
    for spec in INPUTS:
        with_cy = bash_slug(spec["raw"], cygpath=True)
        without_cy = bash_slug(spec["raw"], cygpath=False)
        if with_cy == without_cy:
            vectors.append(_vector(spec, "agnostic", with_cy))
        else:
            vectors.append(_vector(spec, "present", with_cy))
            vectors.append(_vector(spec, "absent", without_cy))

    return {
        "$comment": COMMENT,
        "format_version": FORMAT_VERSION,
        "generator": "tests/slug_vectors.py",
        "implementation": "scripts/lib-slug.sh",
        "generated_with": {"REMEMBER_UTF8_STRICT": "1"},
        "slug_max": SLUG_MAX,
        "vector_count": len(vectors),
        "vectors": vectors,
    }


def render(doc: dict) -> str:
    """The exact bytes of the checked-in file.

    `ensure_ascii=False` so a reviewer reading a diff sees `café`, not
    `caf\\u00e9`. The ill-formed inputs never reach this — they are carried in
    `path_b64` and their `path` is null — so nothing here is unrepresentable.
    """
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    if real_cygpath_on_path():
        print("a real cygpath is on PATH; the no-cygpath half cannot be produced here",
              file=sys.stderr)
        return 1
    VECTOR_FILE.parent.mkdir(parents=True, exist_ok=True)
    VECTOR_FILE.write_text(render(generate()), encoding="utf-8")
    print(f"wrote {VECTOR_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
