export const CLI_COMMAND_TIMEOUT_MS = 3_000;
export const PER_TOOL_FEEDBACK_SAMPLE_RATE = 0.001;
export const PER_TURN_FEEDBACK_SAMPLE_RATE = 0.01;
export const TRANSCRIPT_READ_CHUNK_BYTES = 64 * 1024;
