// Composer tiles. Labelled blanks, not filled examples: they tell the sender what
// the team needs. See SKILL.md for why they omit the chat-routing preamble.

const TASK_PRESETS = [
  { name: 'Call capital', detect: 'capital call',
    requires: [
      { label: 'Fund', has: "fund\\s*:?\\s*\\S|fund\\s+[ivx\\d]" },
      { label: 'Total amount', has: "\\$\\s?[\\d,]|\\bamount\\b[^\\n]*\\d" },
      { label: 'Due date', has: "\\bdue\\b[^\\n]*\\d|\\bdue\\b[^\\n]*(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)" },
      { label: 'Call type', has: "pro-?\\s?rata|subsequent close|in-?\\s?line|hybrid" },
    ],
    template: [
    'Issue a capital call.',
    'Fund:',
    'Total amount:',
    'Due date:',
    'Call type (pro-rata, subsequent close, bring investors in-line, hybrid):',
    'Anything else we should know:',
  ] },
  { name: 'New investment', detect: 'new investment|book an investment',
    requires: [
      { label: 'Fund', has: "fund\\s*:?\\s*\\S|fund\\s+[ivx\\d]" },
      { label: 'Company', has: "\\b(inc|ltd|llc|corp|gmbh)\\b|company\\s*:?\\s*\\S" },
      { label: 'Amount and security', has: "\\$\\s?[\\d,]" },
      { label: 'Close date', has: "\\bclos(e|ed|ing)\\b[^\\n]*\\d|\\bdate\\b[^\\n]*\\d" },
    ],
    template: [
    'Book a new investment.',
    'Fund:',
    'Company:',
    'Amount and security (e.g. $2M Series B preferred):',
    'Close date:',
    'Documents attached or where to find them:',
  ] },
  { name: 'Update valuation', detect: 'valuation|revalue',
    requires: [
      { label: 'Company', has: "\\b(inc|ltd|llc|corp|gmbh)\\b|company\\s*:?\\s*\\S" },
      { label: 'New value', has: "\\$\\s?[\\d,]" },
      { label: 'Effective date', has: "as of[^\\n]*\\d|effective[^\\n]*\\d|\\bdate\\b[^\\n]*\\d" },
    ],
    template: [
    'Update a portfolio company valuation.',
    'Fund:',
    'Company:',
    'New value and basis (e.g. $40M enterprise value):',
    'Effective date:',
    'Supporting source:',
  ] },
  { name: 'Initiate payment', detect: 'pay an invoice|payment|invoice',
    requires: [
      { label: 'Payee', has: "pay(ee)?\\s*:?\\s*\\S|\\binvoice\\b[^\\n]*\\S" },
      { label: 'Amount', has: "\\$\\s?[\\d,]" },
      { label: 'Account to pay from', has: "account\\s*:?\\s*\\S|\\bfrom\\b[^\\n]*\\b(cash|account|bank)\\b" },
    ],
    template: [
    'Pay an invoice.',
    'Fund or entity paying:',
    'Payee:',
    'Amount:',
    'Invoice date and number:',
    'Account to pay from:',
  ] },
  { name: 'Request distribution', detect: 'distribution',
    requires: [
      { label: 'Fund', has: "fund\\s*:?\\s*\\S|fund\\s+[ivx\\d]" },
      { label: 'Total amount', has: "\\$\\s?[\\d,]" },
      { label: 'Allocation basis', has: "pro rata|by commitment|basis\\s*:?\\s*\\S|waterfall" },
      { label: 'Payment date', has: "pa(y|id|yment)[^\\n]*\\d|\\bdate\\b[^\\n]*\\d" },
    ],
    template: [
    'Process a distribution.',
    'Fund:',
    'Total amount:',
    'Allocation basis (e.g. pro rata by commitment):',
    'Payment date:',
    'Anything else we should know:',
  ] },
  { name: 'LP subsequent close', detect: 'subsequent close',
    requires: [
      { label: 'Fund', has: "fund\\s*:?\\s*\\S|fund\\s+[ivx\\d]" },
      { label: 'Close date', has: "\\bclos(e|ing)\\b[^\\n]*\\d|\\bdate\\b[^\\n]*\\d" },
      { label: 'New LPs and commitments', has: "\\$\\s?[\\d,]" },
    ],
    template: [
    'Add a subsequent close.',
    'Fund:',
    'Close date:',
    'New LPs and commitments:',
    'Late interest treatment:',
    'Documents attached or where to find them:',
  ] },
  { name: 'LP transfer', detect: 'transfer',
    requires: [
      { label: 'Fund', has: "fund\\s*:?\\s*\\S|fund\\s+[ivx\\d]" },
      { label: 'Transferring from', has: "\\bfrom\\b[^\\n]*\\S" },
      { label: 'Transferring to', has: "\\bto\\b[^\\n]*\\S" },
      { label: 'Effective date', has: "effective[^\\n]*\\d|\\bdate\\b[^\\n]*\\d" },
    ],
    template: [
    'Transfer an LP commitment.',
    'Fund:',
    'Transferring from:',
    'Transferring to:',
    'Amount or full commitment:',
    'Effective date:',
  ] },
];
