"""Data structures for the memory pipeline.

Defines the core dataclasses used across all pipeline stages: extraction,
summarization, consolidation, and team digest. Each dataclass is a plain
value object with no business logic beyond formatting.

Typical usage::

    from pipeline.types import ExtractResult, TokenUsage

    result = ExtractResult(exchanges="...", position=42, human_count=5)
    usage = TokenUsage(input=1200, output=300, cache=800, cost_usd=0.0021)
    print(usage)  # "1200+800cache→300out ($0.0021)"
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class TokenUsage:
    """Token counts and estimated cost from a single Haiku API call.

    Tracks input, output, and cache-read token counts along with the
    computed USD cost. Used for logging and cost monitoring across all
    pipeline stages.

    Attributes:
        input: Total input tokens sent (includes cached tokens).
        output: Output tokens generated by the model.
        cache: Input tokens served from cache (subset of input).
        cost_usd: Estimated cost in USD, computed from per-token pricing.
    """

    input: int = 0
    output: int = 0
    cache: int = 0
    cost_usd: float = 0.0

    def __str__(self) -> str:
        """Format as a compact summary string for log output."""
        return f"{self.input}+{self.cache}cache->{self.output}out (${self.cost_usd:.4f})"


@dataclass
class HaikuResult:
    """Parsed response from a Haiku CLI invocation.

    Wraps the model's text output along with token usage metadata and
    a flag indicating whether the model chose to skip processing.

    Attributes:
        text: The model's text response (may be empty on error).
        tokens: Token usage and cost for this call.
        is_skip: True if the response starts with "SKIP", indicating
            the model determined there was nothing worth summarizing, or if
            the reject gate matched a refusal-shaped reply.
        is_rejected: True only for the second case. Both are kept out of
            memory, but a rejection discards a span of real work, and the
            caller has to be able to say so — reported as a plain SKIP it is
            indistinguishable from a genuinely empty session, and it slips
            past max_summary_failures too, which only counts hard errors.
        provider: Which summarizer actually produced this result -- "claude"
            or "codex" (#460/#461). Multiple providers exist now, so a SKIP
            in the log is ambiguous about which one declined unless this is
            threaded through: the "was this host-shaped?" question #461 asks
            is only answerable if the log can name which route a given
            verdict came from. Set explicitly by whichever call path built
            this result; the default is "claude" because that was the only
            provider before #460 and every construction site that predates
            it (tests included) is correct leaving it unset.
    """

    text: str = ""
    tokens: TokenUsage = field(default_factory=TokenUsage)
    is_skip: bool = False
    is_rejected: bool = False
    provider: str = "claude"


@dataclass
class ExtractResult:
    """Result of extracting human/assistant exchanges from a session JSONL.

    Produced by ``extract.extract_session()``. Contains the formatted
    exchange text and metadata about what was extracted.

    Attributes:
        exchanges: Formatted text of all extracted exchanges, with role
            headers ([HUMAN] / [AGENT]) and separator lines.
        position: Total line count in the JSONL file (used as the save
            position for incremental extraction).
        human_count: Number of human (user) messages extracted.
        assistant_count: Number of assistant messages extracted.
        corrupt_lines: Number of lines that failed JSON parsing.
        envelope: Which host wrote this transcript's lines, as identified by
            ``pipeline.host.sniff_envelope()`` from the file's own first line
            -- "claude-code", "codex", or "unrecognised". "unrecognised" is
            the loud third state: a shape this module does not know, reported
            rather than silently parsed as a session with nothing in it (#443).
        skip_lines: The JSONL line this extraction actually started reading
            from. Normally the caller's last saved position, but when a prior
            run recorded this session in the unread-envelope quarantine
            (#450 -- an "unrecognised" envelope that advanced the saved
            position anyway, to keep #147's loop closed, without ever having
            read the span), this is that earlier, still-unread point instead
            -- so a later build that CAN parse the envelope re-reads the span
            the earlier build only skipped past. Callers report it (and
            ``save-position`` consumes it) so the quarantine can be cleared
            once something has actually read that span.
        unread_sidecar_unreadable: True when the unread-envelope.json
            quarantine sidecar was consulted for a resume position AND it
            exists but could not be trusted (a torn write, a disk fault, a
            truncated file) -- never true when the sidecar simply does not
            exist, which is the ordinary "nothing was ever quarantined"
            case (#458). A caller resuming as though nothing were
            quarantined when the sidecar is actually corrupt can silently
            re-lose a span #450's quarantine exists to protect.
        envelope_unreadable: True when the transcript file named by
            ``envelope`` could not even be OPENED (an ``OSError`` --
            permission error, bad mount, vanished between listing and
            open) -- never true when the file was opened at all, whether
            that read hit genuine exhaustion (or an empty file) or gave up
            at the scan cap (``envelope_capped``, below), since neither of
            those ever contained a line naming a known host shape (#478,
            #556). ``envelope`` is "unrecognised" in every case; this is
            what tells "could not open it" apart from the other two.
        envelope_capped: True when ``envelope`` is "unrecognised" because
            the scan gave up after ``extract._ENVELOPE_SNIFF_SCAN_CAP``
            parseable-but-unplaceable lines, rather than because the file
            was read to genuine exhaustion (or found empty) without ever
            naming a known host shape (#556). Never true together with
            ``envelope_unreadable`` -- a file that could not be opened
            never reaches the scan -- and never true for a resolved
            envelope. Lets a caller (``pipeline.haiku``'s fallback warning)
            name the cap specifically instead of lumping it in with
            "unrecognised shape".
        envelope_has_unmapped_step: True when ``envelope`` resolved to a
            known host (currently only ever set for "antigravity") but the
            read span contained at least one step whose own ``type`` this
            build's ``pipeline.host`` adapter cannot map to a role (#575).
            Distinct from an ordinary 0-exchange span: that reports the
            same ``human_count``/``assistant_count`` of 0 this can, but
            this is only ever true when a step was actually seen and
            dropped, so a caller (``scripts/save-session.sh``) can route
            such a span through the same #450 quarantine an "unrecognised"
            envelope gets, rather than reporting it as a genuinely quiet
            session that is safe to advance past for good.
    """

    exchanges: str = ""
    position: int = 0
    human_count: int = 0
    assistant_count: int = 0
    corrupt_lines: int = 0
    envelope: str = ""
    skip_lines: int = 0
    unread_sidecar_unreadable: bool = False
    envelope_unreadable: bool = False
    envelope_capped: bool = False
    envelope_has_unmapped_step: bool = False


@dataclass
class SaveResult:
    """Result of a save operation that appends a summary to staging.

    Attributes:
        action: Outcome of the save — one of "appended", "skip", or "error".
        entry: The summary text that was appended (empty on skip/error).
        position: JSONL line position at the time of save.
        tokens: Token usage from the Haiku summarization call.
    """

    action: str = ""       # "appended" | "skip" | "error"
    entry: str = ""        # the text appended (or empty)
    position: int = 0      # JSONL line position
    tokens: TokenUsage = field(default_factory=TokenUsage)


@dataclass
class ConsolidationResult:
    """Result of consolidating staging files into recent and archive memory.

    Produced by ``consolidate.consolidate()``. Contains the new file
    contents that the shell script writes to ``recent.md`` and ``archive.md``.

    Attributes:
        recent: New content for recent.md (active, high-relevance entries).
        archive: New content for archive.md (older, compressed entries).
        tokens: Token usage from the Haiku consolidation call.
    """

    recent: str = ""
    archive: str = ""
    tokens: TokenUsage = field(default_factory=TokenUsage)
