#!/usr/bin/env python3
"""
Generate Figma Plugin API JavaScript for a complete interaction storyboard.

The generated storyboard script creates all screenshot containers, labels,
native annotations, and visual interaction markers in one use_figma call. It
does not embed image bytes. It returns uploadTargets so the agent can upload
optimized screenshots with upload_assets, then run the generated fill script.

Usage:
    python generate_figma_calls.py \
      --prepared /tmp/vim_frames/upload_manifest.json \
      --output-dir /tmp/vim_frames/figma_calls/
"""

import argparse
import datetime
import json
import os
import re
import sys
from pathlib import Path


STORYBOARD_TEMPLATE = r'''// AUTO-GENERATED by generate_figma_calls.py - do not edit manually
// Creates the full interaction storyboard. Upload images separately with upload_assets.
const PAGE_NAME = __PAGE_NAME_JSON__;
const STORYBOARD = __STORYBOARD_JSON__;

let page = figma.root.children.find(p => p.type === "PAGE" && p.name === PAGE_NAME);
if (!page) {
  const reusableBlankPage = figma.root.children.length === 1 ? figma.root.children[0] : null;
  page = reusableBlankPage || figma.createPage();
  page.name = PAGE_NAME;
}
await figma.setCurrentPageAsync(page);

// Make re-runs deterministic for this generated page.
for (const child of [...page.children]) {
  child.remove();
}

await figma.loadFontAsync({ family: "Inter", style: "Regular" });
await figma.loadFontAsync({ family: "Inter", style: "Semi Bold" });
await figma.loadFontAsync({ family: "Inter", style: "Bold" });

const createdNodeIds = [];
const mutatedNodeIds = [page.id];
const uploadTargets = [];

const frameW = STORYBOARD.frameWidth;
const frameH = STORYBOARD.frameHeight;
const GAP = 80;
const MOMENT_GAP = 160;
const TITLE_HEIGHT = 240;
const LABEL_GAP = 16;
const NOTE_GAP = 8;
const ns = "videoInteractionMapper";

const colors = {
  titleBg: { r: 0.067, g: 0.067, b: 0.067 },
  white: { r: 1, g: 1, b: 1 },
  muted: { r: 0.58, g: 0.58, b: 0.62 },
  mutedText: { r: 0.45, g: 0.45, b: 0.45 },
  accent: { r: 0.38, g: 0.38, b: 0.93 },
  frameBg: { r: 0.92, g: 0.92, b: 0.95 },
  frameStroke: { r: 0.78, g: 0.78, b: 0.84 },
  marker: { r: 0.098, g: 0.435, b: 1 },
  inferredMarker: { r: 1.0, g: 0.62, b: 0.05 }
};

const makeText = (chars, size, style, color, x, y, maxWidth, parent = page) => {
  const node = figma.createText();
  node.fontName = { family: "Inter", style };
  node.characters = chars || "";
  node.fontSize = size;
  node.fills = [{ type: "SOLID", color }];
  node.x = x;
  node.y = y;
  if (maxWidth) {
    node.resize(maxWidth, node.height);
    node.textAutoResize = "HEIGHT";
  }
  parent.appendChild(node);
  createdNodeIds.push(node.id);
  return node;
};

const makeUploadFrame = (name, x, y, width, height) => {
  const frame = figma.createFrame();
  frame.name = name;
  frame.resize(width, height);
  frame.x = x;
  frame.y = y;
  frame.fills = [{ type: "SOLID", color: colors.frameBg }];
  frame.strokes = [{ type: "SOLID", color: colors.frameStroke }];
  frame.strokeWeight = 1;
  frame.cornerRadius = 8;
  frame.clipsContent = true;
  page.appendChild(frame);
  createdNodeIds.push(frame.id);
  return frame;
};

const toUnit = (value) => {
  const number = Number(value);
  if (!Number.isFinite(number)) return null;
  return Math.max(0, Math.min(1, number > 1 ? number / 100 : number));
};

const normalizePoint = (point) => {
  if (!point) return null;
  if (Array.isArray(point)) return { x: point[0], y: point[1], label: "" };
  return point;
};

const isUncertainPoint = (point) => {
  const normalized = normalizePoint(point);
  if (!normalized) return false;
  if (normalized.uncertain === true || normalized.inferred === true) return true;
  if (typeof normalized.confidence === "string") {
    return ["medium", "low", "inferred", "uncertain"].includes(normalized.confidence.toLowerCase());
  }
  if (typeof normalized.confidence === "number") {
    return normalized.confidence < 0.85;
  }
  return false;
};

const pointHasCoordinates = (point) => {
  const normalized = normalizePoint(point);
  if (!normalized) return false;
  return toUnit(normalized.x) !== null && toUnit(normalized.y) !== null;
};

const hasExplicitMarkerOverride = (point, value) => {
  const normalized = normalizePoint(point);
  if (!normalized) return false;
  return normalized.marker === value ||
    normalized.draw_marker === value ||
    normalized.drawMarker === value ||
    normalized.show_marker === value ||
    normalized.showMarker === value;
};

const shouldDrawMarker = (point) => {
  const normalized = normalizePoint(point);
  if (!normalized || !pointHasCoordinates(normalized)) return false;
  if (normalized.visible === false || hasExplicitMarkerOverride(normalized, false)) return false;
  if (hasExplicitMarkerOverride(normalized, true)) return true;
  return !isUncertainPoint(normalized);
};

const shouldDrawResultMarker = (point) => {
  return hasExplicitMarkerOverride(point, true);
};

const labelForPoint = (point, fallback) => {
  const normalized = normalizePoint(point);
  const label = normalized && normalized.label ? normalized.label : fallback;
  return isUncertainPoint(normalized) ? `${label} (inferred)` : label;
};

const addInteractionMarker = (frame, point, markerName) => {
  const normalized = normalizePoint(point);
  if (!shouldDrawMarker(normalized)) return null;
  const x = toUnit(normalized.x);
  const y = toUnit(normalized.y);
  if (x === null || y === null) return null;

  const uncertain = isUncertainPoint(normalized);
  const markerColor = uncertain ? colors.inferredMarker : colors.marker;
  const size = uncertain ? 56 : 48;

  const ring = figma.createEllipse();
  ring.name = uncertain ? `${markerName}_inferred` : markerName;
  ring.resize(size, size);
  ring.x = (x * frameW) - (size / 2);
  ring.y = (y * frameH) - (size / 2);
  ring.fills = [{ type: "SOLID", color: markerColor, opacity: uncertain ? 0.1 : 0.14 }];
  ring.strokes = [{ type: "SOLID", color: markerColor }];
  ring.strokeWeight = uncertain ? 3 : 4;
  frame.appendChild(ring);
  createdNodeIds.push(ring.id);

  const dot = figma.createEllipse();
  dot.name = `${ring.name}_dot`;
  dot.resize(10, 10);
  dot.x = (x * frameW) - 5;
  dot.y = (y * frameH) - 5;
  dot.fills = [{ type: "SOLID", color: markerColor }];
  frame.appendChild(dot);
  createdNodeIds.push(dot.id);

  return ring;
};

const getInteractionCategory = async () => {
  if (!figma.annotations) return null;
  const categories = await figma.annotations.getAnnotationCategoriesAsync();
  const existing = categories.find(category => category.label === "Interaction");
  return existing || await figma.annotations.addAnnotationCategoryAsync({
    label: "Interaction",
    color: "blue"
  });
};

const appendNativeAnnotation = (node, labelMarkdown, categoryId) => {
  if (!categoryId) return;
  node.annotations = [
    ...(node.annotations || []),
    { labelMarkdown, categoryId }
  ];
  mutatedNodeIds.push(node.id);
};

const titleBg = figma.createFrame();
titleBg.name = "_title_block";
titleBg.resize(860, 200);
titleBg.x = 0;
titleBg.y = 0;
titleBg.fills = [{ type: "SOLID", color: colors.titleBg }];
titleBg.cornerRadius = 12;
page.appendChild(titleBg);
createdNodeIds.push(titleBg.id);

makeText("Interaction Map", 28, "Bold", colors.white, 32, 32, 780, titleBg);
makeText(STORYBOARD.videoName, 14, "Regular", colors.muted, 32, 80, 780, titleBg);
makeText(STORYBOARD.meta, 12, "Regular", colors.muted, 32, 104, 780, titleBg);
makeText(`${STORYBOARD.moments.length} interaction states extracted`, 14, "Semi Bold", colors.accent, 32, 140, 780, titleBg);

const category = await getInteractionCategory();
let nextX = 0;
const frameY = TITLE_HEIGHT;

for (const moment of STORYBOARD.moments) {
  if (nextX > 0) nextX += MOMENT_GAP - GAP;

  const beforeX = nextX;
  const beforeFrame = makeUploadFrame(moment.beforeLabel, beforeX, frameY, frameW, frameH);
  if (moment.beforePath) {
    uploadTargets.push({
      assetKey: moment.beforeAssetKey,
      momentIndex: moment.momentIndex,
      role: "before",
      nodeId: beforeFrame.id,
      path: moment.beforePath,
      scaleMode: "FILL"
    });
  }
  makeText("Before state", 11, "Regular", colors.mutedText, beforeX, frameY + frameH + LABEL_GAP, frameW);

  nextX = beforeX + frameW + GAP;
  const afterX = nextX;
  const afterFrame = makeUploadFrame(moment.afterLabel, afterX, frameY, frameW, frameH);
  if (moment.afterPath) {
    uploadTargets.push({
      assetKey: moment.afterAssetKey,
      momentIndex: moment.momentIndex,
      role: "after",
      nodeId: afterFrame.id,
      path: moment.afterPath,
      scaleMode: "FILL"
    });
  }

  const interaction = moment.interaction;
  const pickFrame = (name, fallback) => {
    if (name === "after") return afterFrame;
    if (name === "before") return beforeFrame;
    return fallback;
  };

  if (interaction && interaction.target) {
    const targetFrame = pickFrame(interaction.target_frame || interaction.targetFrame, beforeFrame);
    const resultFrame = pickFrame(interaction.result_frame || interaction.resultFrame, afterFrame);
    const targetLabel = labelForPoint(interaction.target, "User action");
    const resultLabel = labelForPoint(interaction.result, "Resulting UI change");
    const summary = interaction.annotation || `${targetLabel} -> ${resultLabel}`;

    const targetMarker = addInteractionMarker(targetFrame, interaction.target, "_interaction_target_marker");
    const targetAnnotationNode = targetMarker || targetFrame;
    appendNativeAnnotation(
      targetAnnotationNode,
      `**Interaction target**\n${summary}\n\nTarget: ${targetLabel}`,
      category && category.id
    );

    if (interaction.result) {
      const resultMarker = shouldDrawResultMarker(interaction.result)
        ? addInteractionMarker(resultFrame, interaction.result, "_interaction_result_marker")
        : null;
      const resultAnnotationNode = resultMarker || resultFrame;
      if (resultAnnotationNode.id !== targetAnnotationNode.id) {
        appendNativeAnnotation(
          resultAnnotationNode,
          `**Interaction result**\n${summary}\n\nResult: ${resultLabel}`,
          category && category.id
        );
      }
    }
  }

  const triggerLabel = makeText(
    moment.afterLabel,
    13,
    "Semi Bold",
    colors.accent,
    afterX,
    frameY + frameH + LABEL_GAP,
    frameW
  );

  makeText(
    moment.annotation,
    11,
    "Regular",
    colors.mutedText,
    afterX,
    frameY + frameH + LABEL_GAP + triggerLabel.height + NOTE_GAP,
    frameW
  );

  nextX = afterX + frameW + GAP;
}

page.setSharedPluginData(ns, "runManifestPath", STORYBOARD.runManifestPath || "");
page.setSharedPluginData(ns, "pageName", PAGE_NAME);
page.setSharedPluginData(ns, "frameWidth", String(frameW));
page.setSharedPluginData(ns, "frameHeight", String(frameH));

figma.viewport.scrollAndZoomIntoView(page.children);

return {
  pageId: page.id,
  pageName: PAGE_NAME,
  createdNodeIds,
  mutatedNodeIds,
  uploadTargets,
  nextX
};
'''


APPLY_FILLS_TEMPLATE = r'''// AUTO-GENERATED by generate_figma_calls.py - do not edit manually
// Paste upload results into uploadedImages, then run this with use_figma.
// Expected item shape: { "nodeId": "3:8", "imageHash": "abc123" }
const uploadedImages = __UPLOAD_RESULTS_JSON__;

if (!uploadedImages.length) {
  throw new Error("No uploaded image hashes supplied. Replace uploadedImages with upload_assets results first.");
}

const mutatedNodeIds = [];
for (const item of uploadedImages) {
  const node = await figma.getNodeByIdAsync(item.nodeId);
  if (!node) {
    throw new Error(`Could not find image target node ${item.nodeId}`);
  }
  node.fills = [{
    type: "IMAGE",
    imageHash: item.imageHash,
    scaleMode: item.scaleMode || "FILL"
  }];
  mutatedNodeIds.push(node.id);
}

return {
  mutatedNodeIds,
  appliedImageCount: mutatedNodeIds.length
};
'''


def safe_filename(value: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_-]", "_", value.lower())
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    return cleaned[:30] or "moment"


def frame_size(prepared: dict) -> tuple[int, int]:
    width = prepared.get("frame_width")
    height = prepared.get("frame_height")
    if width and height:
        return int(width), int(height)

    video_info = prepared.get("video_info", {})
    source_width = int(video_info.get("width", 1440) or 1440)
    source_height = int(video_info.get("height", 810) or 810)
    max_width = 900 if source_height > source_width else 1440
    if source_width > max_width:
        ratio = max_width / source_width
        return max_width, int(source_height * ratio)
    return source_width, source_height


def asset_key(moment_index: int, role: str, label: str) -> str:
    return f"moment-{moment_index:03d}-{role}-{safe_filename(label)}"


def point_has_coordinates(point: object) -> bool:
    if not point:
        return False
    if isinstance(point, list) and len(point) >= 2:
        return True
    if isinstance(point, dict):
        return point.get("x") is not None and point.get("y") is not None
    return False


def point_label(point: object, fallback: str) -> str:
    if isinstance(point, dict) and point.get("label"):
        return str(point["label"])
    return fallback


def point_value(point: object, key: str) -> object:
    if isinstance(point, dict):
        return point.get(key)
    return None


def point_marker_override(point: object) -> bool | None:
    if not isinstance(point, dict):
        return None
    for key in ("marker", "draw_marker", "drawMarker", "show_marker", "showMarker"):
        if key in point:
            return bool(point[key])
    return None


def point_is_uncertain(point: object) -> bool:
    if not isinstance(point, dict):
        return False
    if point.get("uncertain") is True or point.get("inferred") is True:
        return True
    confidence = point.get("confidence")
    if isinstance(confidence, str):
        return confidence.lower() in {"medium", "low", "inferred", "uncertain"}
    if isinstance(confidence, (int, float)):
        return confidence < 0.85
    return False


def point_marker_decision(point: object, *, default_draw: bool = True) -> str:
    if not point_has_coordinates(point):
        return "skipped_no_coordinates"
    if isinstance(point, dict) and point.get("visible") is False:
        return "skipped_not_visible"
    override = point_marker_override(point)
    if override is False:
        return "skipped_by_marker_override"
    if override is True:
        return "drawn_by_marker_override"
    if point_is_uncertain(point):
        return "skipped_uncertain"
    return "drawn" if default_draw else "skipped_default_result_annotation"


def build_storyboard(prepared: dict, page_name: str, run_manifest_path: str) -> tuple[dict, list[dict]]:
    frame_w, frame_h = frame_size(prepared)
    video_path = prepared.get("video_path", "unknown")
    video_name = os.path.basename(video_path)
    total_moments = prepared.get("total_moments", len(prepared.get("moments", [])))
    generated_at = datetime.datetime.now().isoformat(timespec="seconds")
    meta = f"{total_moments} key moments - {generated_at[:10]}"

    moments_out = []
    expected_uploads = []

    for index, moment in enumerate(prepared.get("moments", []), start=1):
        moment_index = int(moment.get("moment_index", index))
        short_label = moment.get("short_label", f"Moment {moment_index}")
        trigger_marker = moment.get("trigger_emoji", "")
        before_path = moment.get("before_upload_path") or moment.get("before_frame_path")
        after_path = moment.get("after_upload_path") or moment.get("after_frame_path")
        before_key = asset_key(moment_index, "before", short_label)
        after_key = asset_key(moment_index, "after", short_label)
        after_label = f"{moment_index:02d} {trigger_marker} {short_label}".replace("  ", " ").strip()

        moments_out.append(
            {
                "momentIndex": moment_index,
                "timestampS": moment.get("timestamp_s"),
                "trigger": moment.get("trigger"),
                "shortLabel": short_label,
                "annotation": moment.get("annotation", ""),
                "beforeLabel": f"Before - {short_label}",
                "afterLabel": after_label,
                "beforePath": before_path,
                "afterPath": after_path,
                "beforeAssetKey": before_key,
                "afterAssetKey": after_key,
                "interaction": moment.get("interaction"),
            }
        )

        if before_path:
            expected_uploads.append(
                {
                    "assetKey": before_key,
                    "momentIndex": moment_index,
                    "role": "before",
                    "path": before_path,
                    "scaleMode": "FILL",
                    "nodeId": None,
                    "imageHash": None,
                    "status": "pending",
                }
            )
        if after_path:
            expected_uploads.append(
                {
                    "assetKey": after_key,
                    "momentIndex": moment_index,
                    "role": "after",
                    "path": after_path,
                    "scaleMode": "FILL",
                    "nodeId": None,
                    "imageHash": None,
                    "status": "pending",
                }
            )

    storyboard = {
        "videoName": video_name,
        "videoPath": video_path,
        "generatedAt": generated_at,
        "meta": meta,
        "frameWidth": frame_w,
        "frameHeight": frame_h,
        "runManifestPath": run_manifest_path,
        "moments": moments_out,
    }

    return storyboard, expected_uploads


def build_run_manifest(
    prepared: dict,
    storyboard: dict,
    expected_uploads: list[dict],
    page_name: str,
    storyboard_script: str,
    fill_script_template: str,
) -> dict:
    selected_moments = []
    for moment in prepared.get("moments", []):
        interaction = moment.get("interaction") or {}
        target = interaction.get("target") if isinstance(interaction, dict) else None
        result = interaction.get("result") if isinstance(interaction, dict) else None
        selected_moments.append(
            {
                "moment_index": moment.get("moment_index"),
                "timestamp_s": moment.get("timestamp_s"),
                "short_label": moment.get("short_label"),
                "before_upload_path": moment.get("before_upload_path"),
                "after_upload_path": moment.get("after_upload_path"),
                "interaction": {
                    "target_frame": interaction.get("target_frame") or interaction.get("targetFrame"),
                    "target_label": point_label(target, "User action") if target else None,
                    "target_has_coordinates": point_has_coordinates(target),
                    "target_confidence": point_value(target, "confidence"),
                    "target_inferred": bool(point_value(target, "inferred")),
                    "target_uncertain": bool(point_value(target, "uncertain")),
                    "target_visible": point_value(target, "visible"),
                    "target_marker_decision": point_marker_decision(target),
                    "result_frame": interaction.get("result_frame") or interaction.get("resultFrame"),
                    "result_label": point_label(result, "Resulting UI change") if result else None,
                    "result_has_coordinates": point_has_coordinates(result),
                    "result_confidence": point_value(result, "confidence"),
                    "result_inferred": bool(point_value(result, "inferred")),
                    "result_uncertain": bool(point_value(result, "uncertain")),
                    "result_visible": point_value(result, "visible"),
                    "result_marker_decision": point_marker_decision(result, default_draw=False),
                } if interaction else None,
            }
        )

    return {
        "schema_version": 1,
        "pipeline": "upload-assets-combined-storyboard",
        "generated_at": storyboard["generatedAt"],
        "video_path": prepared.get("video_path"),
        "page_name": page_name,
        "image_budget": prepared.get("image_budget"),
        "frame_width": storyboard["frameWidth"],
        "frame_height": storyboard["frameHeight"],
        "selected_moments": selected_moments,
        "figma": {
            "storyboard_script": storyboard_script,
            "fill_script_template": fill_script_template,
            "page_id": None,
            "created_node_ids": [],
            "upload_targets": [],
            "uploaded_images": [],
            "fill_pass": {"status": "pending", "mutated_node_ids": []},
            "verification": {"status": "pending", "screenshot_path": None, "notes": ""},
        },
        "stages": {
            "local_assets": "complete",
            "storyboard": "pending",
            "uploads": "pending",
            "fills": "pending",
            "verification": "pending",
        },
        "expected_uploads": expected_uploads,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate combined Figma Plugin API JS files")
    parser.add_argument("--prepared", required=True, help="Path to upload_manifest.json")
    parser.add_argument("--output-dir", required=True, help="Directory to write generated files")
    parser.add_argument("--page-name", help="Optional Figma page name. Defaults to a timestamped page name.")
    args = parser.parse_args()

    with open(args.prepared) as f:
        prepared = json.load(f)

    moments = prepared.get("moments", [])
    if not moments:
        print("Error: upload manifest has no moments", file=sys.stderr)
        sys.exit(1)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    video_path = prepared.get("video_path", "unknown")
    video_name = os.path.basename(video_path)
    video_stem = os.path.splitext(video_name)[0][:48] or "video"
    now = datetime.datetime.now()
    page_name = args.page_name or f"Interaction Map - {video_stem} - {now.strftime('%Y-%m-%d %H%M%S')}"

    storyboard_script_path = output_dir / "figma_storyboard.js"
    fill_script_template_path = output_dir / "figma_apply_fills_template.js"
    run_manifest_path = output_dir / "run_manifest.json"

    storyboard, expected_uploads = build_storyboard(prepared, page_name, str(run_manifest_path))
    storyboard_js = STORYBOARD_TEMPLATE.replace("__PAGE_NAME_JSON__", json.dumps(page_name))
    storyboard_js = storyboard_js.replace("__STORYBOARD_JSON__", json.dumps(storyboard, separators=(",", ":")))
    storyboard_script_path.write_text(storyboard_js)

    fill_template = APPLY_FILLS_TEMPLATE.replace("__UPLOAD_RESULTS_JSON__", "[]")
    fill_script_template_path.write_text(fill_template)

    run_manifest = build_run_manifest(
        prepared,
        storyboard,
        expected_uploads,
        page_name,
        str(storyboard_script_path),
        str(fill_script_template_path),
    )
    run_manifest_path.write_text(json.dumps(run_manifest, indent=2))

    manifest = {
        "total_calls": 2,
        "page_name": page_name,
        "storyboard_script": str(storyboard_script_path),
        "fill_script_template": str(fill_script_template_path),
        "run_manifest": str(run_manifest_path),
        "expected_uploads": expected_uploads,
        "instructions": (
            "Run storyboard_script with use_figma once. Upload every returned uploadTargets item "
            "with upload_assets. Record nodeId/imageHash pairs, replace uploadedImages in "
            "fill_script_template, and run that fill script once. Coordinates remain in the "
            "interaction metadata for marker placement, but native annotation text hides them. "
            "Target markers draw by default; result markers only draw when explicitly requested."
        ),
    }
    manifest_path = output_dir / "figma_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))

    print(f"Generated combined storyboard for {len(moments)} moments")
    print(f"  Storyboard script: {storyboard_script_path} ({len(storyboard_js):,} chars)")
    print(f"  Fill script template: {fill_script_template_path}")
    print(f"  Run manifest: {run_manifest_path}")
    print(f"  Execution manifest: {manifest_path}")


if __name__ == "__main__":
    main()
